Config = {}

Config.AttachmentCrafting = {
    ['location'] = vector3(88.91, 3743.88, 40.77), 
    ["items"] = {
        [1] = {
            name = "pistol_extendedclip",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 140,
                ["steel"] = 250,
                ["rubber"] = 60,
            },
            type = "item",
            slot = 1,
            threshold = 0,
            points = 1,
        },
        [2] = {
            name = "pistol_suppressor",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 165,
                ["steel"] = 285,
                ["rubber"] = 75,
            },
            type = "item",
            slot = 2,
            threshold = 10,
            points = 2,
        },
        [3] = {
            name = "assaultrifle_extendedclip",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 190,
                ["steel"] = 305,
                ["rubber"] = 85,
                ["smg_extendedclip"] = 1,
            },
            type = "item",
            slot = 3,
            threshold = 25,
            points = 8,
        },
        [4] = {
            name = "assaultrifle_drum",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 205,
                ["steel"] = 340,
                ["rubber"] = 110,
                ["smg_extendedclip"] = 2,
            },
            type = "item",
            slot = 4,
            threshold = 50,
            points = 8,
        },
        [5] = {
            name = "smg_drum",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 230,
                ["steel"] = 365,
                ["rubber"] = 130,
            },
            type = "item",
            slot = 5,
            threshold = 75,
            points = 3,
        },
        [6] = {
            name = "smg_extendedclip",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 255,
                ["steel"] = 390,
                ["rubber"] = 145,
            },
            type = "item",
            slot = 6,
            threshold = 100,
            points = 4,
        },
        [7] = {
            name = "microsmg_extendedclip",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 270,
                ["steel"] = 435,
                ["rubber"] = 155,
            },
            type = "item",
            slot = 7,
            threshold = 150,
            points = 5,
        },
        [8] = {
            name = "smg_scope",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 300,
                ["steel"] = 469,
                ["rubber"] = 170,
            },
            type = "item",
            slot = 8,
            threshold = 200,
            points = 6,
        },
    }
}

Config.CraftingItems = {
    ['locatie'] = vector3(1534.17, 3586.95, 38.87),
    ["iteme"] = {
        [1] = {
            name = "lockpick",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 22,
                ["plastic"] = 32,
            },
            type = "item",
            slot = 1,
            threshold = 0,
            points = 1,
        },
        [2] = {
            name = "screwdriverset",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 30,
                ["plastic"] = 42,
            },
            type = "item",
            slot = 2,
            threshold = 2,
            points = 2,
        },
        [3] = {
            name = "electronickit",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 30,
                ["plastic"] = 45,
                ["aluminum"] = 28,
            },
            type = "item",
            slot = 3,
            threshold = 3,
            points = 3,
        },
        [4] = {
            name = "gatecrack",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 10,
                ["plastic"] = 50,
                ["aluminum"] = 30,
                ["iron"] = 17,
                ["electronickit"] = 1,
            },
            type = "item",
            slot = 4,
            threshold = 10,
            points = 4,
        },
        [5] = {
            name = "handcuffs",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 36,
                ["steel"] = 24,
                ["aluminum"] = 28,
            },
            type = "item",
            slot = 5,
            threshold = 20,
            points = 6,
        },
        [6] = {
            name = "armor",
            amount = 50,
            info = {},
            costs = {
                ["iron"] = 33,
                ["steel"] = 44,
                ["plastic"] = 55,
                ["aluminum"] = 22,
            },
            type = "item",
            slot = 11,
            threshold = 50,
            points = 8,
        },
        [7] = {
            name = "drill",
            amount = 50,
            info = {},
            costs = {
                ["iron"] = 50,
                ["steel"] = 50,
                ["screwdriverset"] = 3,
                ["advancedlockpick"] = 2,
            },
            type = "item",
            slot = 7,
            threshold = 80,
            points = 12,
        },
        [8] = {
            name = "weapon_pipebomb",
            amount = 50,
            info = {},
            costs = {
                ["rolex"] = 2,
                ["steel"] = 50,
                ["armor"] = 3,
                ["advancedlockpick"] = 2,
            },
            type = "item",
            slot = 8,
            threshold = 90,
            points = 16,
        },
        [9] = {
            name = "goldenphone",
            amount = 50,
            info = {},
            costs = {
                ["goldbar"] = 5,
                ["electronickit"] = 2,
                ["gatecrack"] = 5,
                ["advancedlockpick"] = 2,
            },
            type = "item",
            slot = 9,
            threshold = 110,
            points = 20,
        },
    }
   
}
